---
# Especifico do grupo windows (Windows Server 2022).
# USUARIO e SENHA vem da Machine Credential (WinRM) do AWX (NAO versionar).
ansible_connection: winrm
ansible_port: 5986
ansible_user: Administrator
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore # cert self-signed criado no boot

# Servico / config do Zabbix Agent 2 no Windows.
zabbix_agent_service_name: Zabbix Agent 2
zabbix_agent_config_path: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
